// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// permutedPertScore_RCPP
List permutedPertScore_RCPP(const arma::mat& X, const CharacterVector& pathwayG, const CharacterVector& expressedG, const List& permutedFC, int newS);
RcppExport SEXP _SSPT_permutedPertScore_RCPP(SEXP XSEXP, SEXP pathwayGSEXP, SEXP expressedGSEXP, SEXP permutedFCSEXP, SEXP newSSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type pathwayG(pathwayGSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type expressedG(expressedGSEXP);
    Rcpp::traits::input_parameter< const List& >::type permutedFC(permutedFCSEXP);
    Rcpp::traits::input_parameter< int >::type newS(newSSEXP);
    rcpp_result_gen = Rcpp::wrap(permutedPertScore_RCPP(X, pathwayG, expressedG, permutedFC, newS));
    return rcpp_result_gen;
END_RCPP
}
// ssPertScore_RCPP
List ssPertScore_RCPP(const List& BminsI, arma::mat weightedFC, const CharacterVector& expressedG, const CharacterVector& sample);
RcppExport SEXP _SSPT_ssPertScore_RCPP(SEXP BminsISEXP, SEXP weightedFCSEXP, SEXP expressedGSEXP, SEXP sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type BminsI(BminsISEXP);
    Rcpp::traits::input_parameter< arma::mat >::type weightedFC(weightedFCSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type expressedG(expressedGSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type sample(sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(ssPertScore_RCPP(BminsI, weightedFC, expressedG, sample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SSPT_permutedPertScore_RCPP", (DL_FUNC) &_SSPT_permutedPertScore_RCPP, 5},
    {"_SSPT_ssPertScore_RCPP", (DL_FUNC) &_SSPT_ssPertScore_RCPP, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SSPT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
