#' @title Simulate permuted perturbation scores
#'
#' @description Simulate null distributions of perturbation scores for each pathway through sample permutation.
#'
#' @details
#' This function firstly randomly permute sample labels NB times to generate permuted logFCs, which are then used to compute permuted perturbation
#' scores for each pathway. The function outputs a list that is of the same length as the list storing pathway topology matrices. Each
#' element of the output list is for a pathway and contains a vector of permuted perturbation score of length NB. It's assumed that the
#' permuted perturbation scores can be used to estimate the null distributions of perturbation scores.
#'
#' The input logCPM matrix should be identical to the input used for `weight_ssFC` function. If the requested number of permutation (NB) is larger than the maximum number of permutations possible, NB will be set to the largest
#' number of permutations possible instead.
#'
#' @param logCPM Matrix of normaslised logCPM where rows are genes and columns are samples. Row names need to be gene entrez IDs.
#' @param numOfTreat Number of treatments (including control)
#' @param NB Number of permutations
#' @param gsTopology List of pathway topology matrices generated using function `weightedAdjMatrix`
#' @param weight A vector of gene-wise weights derived from function `weight_ssFC`
#'
#' @import Rcpp
#' @return A list where each element is a vector of perturbation scores for a pathway.
#' @export
#'
#' @examples
#' require(AnnotationHub)
#' require(ensembldb)
#' # convert rownamews of logCPM from gene ids to gene entrez IDs through `AnnotationHub`
#' ah <- AnnotationHub()
#' ah <- subset(ah,genome == "GRCh38" & title == "Ensembl 101 EnsDb for Homo sapiens")
#' ensDb <- ah[[1]]
#' rownames(logCPM_example) <- mapIds(ensDb, rownames(logCPM_example), "ENTREZID", keytype = "GENEID")
#'
#' # Remove genes that couldn't be matched to entrez IDs
#' logCPM_example <- logCPM_example[!is.na(rownames(logCPM_example)),]
#'
#' #compute weighted single sample logFCs
#' ls <- weight_ssFC(logCPM_example, metadata = metadata_example,
#'  factor = "patient", control = "Vehicle")
#'
#' # explore all species and databases supported by graphite
#' \dontrun{
#' load(system.file("extdata", "gsTopology.rda", package = "SSPT"))
#'  permutedScore <- generate_PermutedScore(logCPM_example, numOfTreat = 2,
#'  NB = 100, gsTopology = gsTopology, weight = ls$weight)
#'  }

generate_PermutedScore <- function(logCPM, numOfTreat,
                                        NB = 1000,
                                        gsTopology, weight){

    # checks

    m <- min(logCPM)
    if (is.na(m)) stop("NA values not allowed")

    if ( ncol(logCPM) %% numOfTreat != 0 ) stop ("Number of samples must be divisible by the number of treatments")
    if (nrow(logCPM) != length(weight)) stop("Gene-wise weights do not match with the dimension of logCPM")
    logCPM <- as.matrix(logCPM)

    rownames(logCPM) <- paste("ENTREZID:", rownames(logCPM), sep = "")
    if (length(intersect(rownames(logCPM), unlist(unname(lapply(gsTopology, rownames))))) == 0)
        stop("None of the expressed gene was matched to pathways. Check if gene identifiers match")

    # test if the required number of permutations is bigger than the maximum number of permutations possible
    NB <- min(NB, factorial(ncol(logCPM)))

    # set expression values and weights of unexpressed pathway genes to 0
    notExpressed <- setdiff(unique(unlist(unname(lapply(gsTopology, rownames)))), rownames(logCPM))
    if (length(notExpressed) != 0){
        temp <- matrix(0, nrow = length(notExpressed), ncol = ncol(logCPM))
        rownames(temp) <- notExpressed
        colnames(temp) <- colnames(logCPM)
        logCPM <- rbind(logCPM, temp)
        weight <- c(weight, rep(0, length(notExpressed)))

    }

    permutedPertScore_RCPP(gsTopology, expressedG = rownames(logCPM), LogCPM = logCPM,
                           NB = NB, sEachp = numOfTreat, weight = weight)
    # permutedScore <- permutedScore[!sapply(permutedScore, is.null)]


}


#' Title
#'
#' @param permutedFC
#' @param gsTopology
#' @param ncores
#'
#' @return
#' @export
#'
#' @examples
permutedScore_PARALLEL <- function(permutedFC, gsTopology, ncores, tol = 1e-7){

    BPPARAM <- BiocParallel::registered()[[1]]
    BPPARAM$workers <- ncores
    BiocParallel::bplapply(gsTopology, function(x){
      as.vector(sapply(permutedFC, function(y){.ssPertScore(x, y)}))
    }, BPPARAM = BPPARAM)
}

#' @title Normalise test perturbation scores by permutation
#'
#' @details Normalise the test perturbation scores generated by `weight_ssFC` through the permuted perturbation scores derived from
#' the `generate_PermutedScore` function. The mean absolute deviation(MAD) and median of perturbation scores for each pathway are firstly
#' derived from the permuted perturbation scores. The test perturbation scores are then converted to robust z-scores using MADs and medians
#' calculated.
#' @param permutedScore A list. Output of `generate_PermutedScore`
#' @param testScore A matrix. Output of `weight_ssFC`
#' @param pAdj_method Method for adjusting p-values for multiple comparisons. See `?p.adjust` for methods available. Default to FDR.
#'
#' @importFrom stats mad median p.adjust pnorm
#' @importFrom dplyr left_join mutate
#' @return A dataframe.
#' @export
#'
#' @examples
#' \dontrun{
#' load(system.file("extdata", "gsTopology.rda", package = "SSPT"))
#' ssPertScore <- perturbationScore(ls$logFC, gsTopology)
#' permutedScore <- generate_PermutedScore(logCPM_example, numOfTreat = 2,
#'  NB = 100, gsTopology = gsTopology, weight = ls$weight)
#' normalisedScores <- normaliseByPermutation(permutedScore, ssPertScore)
#'  }
#' load(system.file("extdata", "normalisedScores.rda", package = "SSPT"))
#' head(normalisedScores)
normaliseByPermutation <- function(permutedScore, testScore, pAdj_method = "fdr"){
    pvalue <- NULL
    summary_func <- function(x){c(MAD = mad(x), MEDIAN = median(x))}
    summaryScore <- as.data.frame(t(sapply(permutedScore, summary_func)))
    summaryScore <- rownames_to_column(summaryScore,"gs_name")
    summaryScore <- filter(summaryScore, summaryScore$MAD != 0)
    summaryScore <- left_join(summaryScore, testScore, by = "gs_name")
    summaryScore <- mutate(summaryScore,
           robustZ = (summaryScore$tA - summaryScore$MEDIAN)/summaryScore$MAD)
    summaryScore <- mutate(summaryScore,
           pvalue = 2*pnorm(-abs(summaryScore$robustZ)))
    summaryScore <- split(summaryScore, f = summaryScore$sample)
    summaryScore <-lapply(summaryScore, mutate, adjPvalue = p.adjust(pvalue, pAdj_method))
    bind_rows(summaryScore)

}


#' #' Title
#' #'
#' #' @param logCPM
#' #' @param metadata
#' #' @param factor
#' #' @param control
#' #' @param BPPARAM
#' #' @param seed
#' #'
#' #' @return
#' #'
#' #' @examples
.generate_permutedFC <- function(logCPM, metadata, factor, control, weight, NB, seed, ncores = 6){
    metadata <- as.data.frame(metadata)
    pairs <- unique(metadata[,factor])
    sampleInpairs <- sapply(pairs, function(x){
        contrSample <- dplyr::filter(metadata, treatment == control, !!sym(factor) == x)
        contrSample <- pull(contrSample, sample)

        treatedSample <- dplyr::filter(metadata, treatment != control, !!sym(factor) == x)
        treatedSample <- pull(treatedSample, sample)
        list(contrSample = contrSample, treatedSample = treatedSample)
    }, simplify = FALSE)

    nSample <- nrow(metadata)

    logCPM <- as.matrix(logCPM)

    rownames(logCPM) <- paste("ENTREZID:", rownames(logCPM), sep = "")
    if (length(intersect(rownames(logCPM), unlist(unname(lapply(gsTopology, rownames))))) == 0)
        stop("None of the expressed gene was matched to pathways. Check if gene identifiers match")

    # test if the required number of permutations is bigger than the maximum number of permutations possible
    NB <- min(NB, factorial(ncol(logCPM)))

    # set expression values and weights of unexpressed pathway genes to 0
    notExpressed <- setdiff(unique(unlist(unname(lapply(gsTopology, rownames)))), rownames(logCPM))
    if (length(notExpressed) != 0){
        temp <- matrix(0, nrow = length(notExpressed), ncol = ncol(logCPM))
        rownames(temp) <- notExpressed
        colnames(temp) <- colnames(logCPM)
        logCPM <- rbind(logCPM, temp)
        weight <- c(weight, rep(0, length(notExpressed)))

    }

    set.seed(seed)

    BPPARAM <- BiocParallel::registered()[[1]]
    BPPARAM$workers <- ncores

    BiocParallel::bplapply(1:NB, function(x){
        # permute sample labels to get permuted logCPM
        colnames(logCPM) <- sample(colnames(logCPM), ncol(logCPM))

        # Built permuted logFCs based on the permuted logCPM
        permutedFC <- sapply(names(sampleInpairs), function(y){
            logCPM[, sampleInpairs[[y]]$treatedSample] - logCPM[, sampleInpairs[[y]]$contrSample]
        }, simplify = FALSE)
        permutedFC <- do.call(cbind,permutedFC)

        # Multiply permuted FCs by gene-wise weights
        permutedFC * weight

    }, BPPARAM = BPPARAM)

}

#' Title
#'
#' @param permutedFC
#' @param gsTopology
#' @param ncores
#'
#' @return
#' @export
#'
#' @examples
permutedScore_Rcpp_para <- function(permutedFC, gsTopology, ncores, tol = 1e-7){

    expressedG <- rownames(permutedFC[[1]])
    newS <-  ncol(permutedFC[[1]])
    BPPARAM <- BiocParallel::registered()[[1]]
    BPPARAM$workers <- ncores

    BiocParallel::bplapply(gsTopology, function(x){
        permutedPertScore_RCPP_indiPathway(X = x, pathwayG = rownames(x), expressedG,
                                           permutedFC = permutedFC, newS)
    }, BPPARAM = BPPARAM)
}


#' Title
#'
#' @param permutedFC
#' @param gsTopology
#' @param ncores
#'
#' @return
#' @export
#'
#' @examples
permutedScore_Rcpp <- function(permutedFC, gsTopology, tol = 1e-7){

    expressedG <- rownames(permutedFC[[1]])
    newS <-  ncol(permutedFC[[1]])

    lapply(gsTopology, function(x){
        permutedPertScore_RCPP_indiPathway(X = x, pathwayG = rownames(x), expressedG,
                                           permutedFC = permutedFC, newS)
    })
}

# permutedFC <- .generate_permutedFC(logCPM_example,metadata_example, "patient", "Vehicle", weightedFC$weight, NB = 10,
#                                    ncores = 4, seed = 123)
# permutedScore <- permutedScore_Rcpp_para(permutedFC, gsTopology, ncores = 4)


# microbenchmark(
#     # "Parallel_4core" = {
#     #     permutedFC <- .generate_permutedFC(logCPM_example,metadata_example, "patient", "Vehicle", weightedFC$weight, NB = 10,
#     #                                       ncores = 4, seed = 123)
#     #     test1 <- permutedScore_PARALLEL(permutedFC, gsTopology, ncores = 4)},
#     "Rcpp_para" = {
#         permutedFC <- .generate_permutedFC(logCPM_example,metadata_example, "patient", "Vehicle", weightedFC$weight, NB = 10,
#                                           ncores = 8, seed = 123)
#         test1 <- permutedScore_Rcpp_para(permutedFC, gsTopology, ncores = 8)},
#     "Rcpp_Nopara" = {
#         permutedFC <- .generate_permutedFC(logCPM_example,metadata_example, "patient", "Vehicle", weightedFC$weight, NB = 10,
#                                            ncores = 8, seed = 123)
#         test2 <- permutedScore_Rcpp(permutedFC, gsTopology)},
#     "Rcpp_allin1"  = {test3 <- generate_PermutedScore(logCPM_example, numOfTreat = 3, NB = 10, gsTopology = gsTopology, weight = weightedFC$weight)},
#     times = 2
# )
#
microbenchmark(
    "passByValue" = {test1 <- permutedScore_Rcpp_para(permutedFC, gsTopology, ncores = 8)},

    "passByRef" = {test2 <- permutedScore_Rcpp_para_alt(permutedFC, gsTopology, ncores = 8)},
    times = 3
)

